language: sh
os: windows
script:
  - powershell -c 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted'
  - powershell -c '.\checkdiskspace.ps1'
  - powershell -c 'Get-ComputerInfo'
  - powershell -c '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; wget https://github.com/dropbox/dbxcli/releases/download/v3.0.0/dbxcli-windows-amd64.exe -OutFile dbxcli-windows-amd64.exe'
  - powershell -c '$pathvargs = {dbxcli-windows-amd64.exe /S /v/qn }; Invoke-Command -ScriptBlock $pathvargs'
  - powershell -c 'dbxcli --help'
